export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const ACCOUNT_DELETE = 'ACCOUNT_DELETE'
export const GET_PROFILES = 'GET_PROFILES'
export const GET_POSTS = 'GET_POSTS'
export const POST_ERROR = 'POST_ERROR'
export const UPDATE_LIKES = 'UPDATE_LIKES'
export const DELETE_POST = 'DELETE_POST'
export const ADD_POST = 'ADD_POST'
export const GET_POST = 'GET_POST'
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'
export const PACKAGE_ERROR = 'PACKAGE_ERROR';
export const GET_PACKAGE_USERS = 'GET_PACKAGE_USERS';
export const PACKGAE_USER_ERROR = 'PACKGAE_USER_ERROR';
export const GET_PACKAGES_USER_BY_ID = 'GET_PACKAGES_USER_BY_ID';
export const REMOVE_PACKAGE = 'REMOVE_PACKAGE';
export const ADD_PACKAGE = 'ADD_PACKAGE';
export const ADD_SESSION = 'ADD_SESSION';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';
export const GET_CURRENT_PACKAGE = 'GET_CURRENT_PACKAGE';
export const CLEAR_CURRENT_PACKAGE = 'CLEAR_CURRENT_PACKAGE';
export const GET_SESSIONS_BY_PACKAGE_ID = 'GET_SESSIONS_BY_PACKAGE_ID';
export const GET_USER_PACKAGES_USER_ID = 'GET_USER_PACKAGES_USER_ID';
export const GET_USER_SESSIONS_BY_PACKAGE_ID = 'GET_USER_SESSIONS_BY_PACKAGE_ID';
export const GET_USER_SINGLE_SESSION_BY_USER_ID = 'GET_USER_SINGLE_SESSION_BY_USER_ID';
export const ADMIN_GET_USER_PROFILE = 'ADMIN_GET_USER_PROFILE';
export const ADMIN_UPDATE_PROFILE = 'ADMIN_UPDATE_PROFILE';
export const GET_SINGLE_SESSION_BY_USER_ID = 'GET_SINGLE_SESSION_BY_USER_ID'
export const ADD_SINGLE_SESSION = 'ADD_SINGLE_SESSION'
export const REMOVE_SINGLE_SESSION = 'REMOVE_SINGLE_SESSION'
export const REMOVE_SESSION_PACKAGE = 'REMOVE_SESSION_PACKAGE'
export const SESSION_ERROR = 'SESSION_ERROR'


export const GET_LASTEST_PACKAGE = 'GET_LASTEST_PACKAGE'
export const BOOKING_UPDATE = 'BOOKING_UPDATE'
export const CLEAR_BOOKING_FORM = 'CLEAR_BOOKING_FORM'
export const GET_BOOKING_CALDENDAR_EVENTS = 'GET_BOOKING_CALDENDAR_EVENTS'
export const BOOKING_MADE = 'BOOKING_MADE'


export const GET_BOOKING_CALENDAR_EVENTS = 'GET_BOOKING_CALENDAR_EVENTS'
export const UPDATE_BOOKING_CALENDAR_EVENT = 'UPDATE_BOOKING_CALENDAR_EVENT'
export const REMOVE_BOOKING_CALENDAR_EVENT = 'REMOVE_BOOKING_CALENDAR_EVENT'
export const GET_BOOKING_CALENDAR_USERS = 'GET_BOOKING_CALENDAR_USERS'
export const GET_BOOKING_CALENDAR_LATEST_PACKAGE = 'GET_BOOKING_CALENDAR_LATEST_PACKAGE'
export const BOOKING_CALENDAR_UPDATE = 'BOOKING_CALENDAR_UPDATE'
export const ADD_BOOKING_CALENDAR_EVENTS = 'ADD_BOOKING_CALENDAR_EVENTS'
export const SUBMIT_CONFIRMED_BOOKINGS_SUCCESS = 'SUBMIT_CONFIRMED_BOOKINGS_SUCCESS'
export const GET_CONFIRMED_BOOKINGS = 'GET_CONFIRMED_BOOKINGS'

export const GET_UP_AND_COMING_CONFIRMED_BOOKINGS = 'GET_UP_AND_COMING_CONFIRMED_BOOKINGS'
export const CANCEL_BOOKING = 'CANCEL_BOOKING'
export const BOOKING_MANAGE_UPDATE = 'BOOKING_MANAGE_UPDATE'//UPDATE_BOOKING
export const REMOVE_BOOKING = 'REMOVE_BOOKING'


export const UPDATE_CONTACT = 'UPDATE_CONTACT'

